version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: gojobberx
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - default

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_URL=postgres://postgres:password@postgres:5432/gojobberx?sslmode=disable
    ports:
      - "8080:8080"
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
    name: gojobberx_net
